services:
  ksef:
    build: .
    volumes:
      - ./certs:/certs:ro
      - ./output:/output
      - ./meta:/app/meta
    command:
      - --nip
      - "9522246503"
      - --token-file
      - /certs/token.txt
      - --download-pdf
      - --pdf-output-dir
      - /output
